name: Generate PDF Resume

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer pagedjs pagedjs-cli

      - name: Generate PDF
        run: |
          mkdir -p docs
          cat > pagedjs-config.js << 'EOL'
          module.exports = {
            page: {
              width: 210,
              height: 297,
              margin: {
                top: 10,
                right: 10,
                bottom: 10,
                left: 10
              }
            }
          };
          EOL
          npx pagedjs-cli index.html -o docs/pdf.pdf --config pagedjs-config.js

      - name: Commit and push PDF
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add -f docs/pdf.pdf
          git commit -m "Update generated PDF resume [$(date)]" || echo "No changes to commit"
          git push