name: Generate PDF Resume

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Convert HTML to PDF
        uses: narthanaj/html-to-pdf-action@v1.0.0
        with:
          source: index.html
          output: docs/pdf.pdf
          format: 'A4'
          print_background: 'true'

      - name: Commit and push PDF
        run: |
          mkdir -p docs
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add -f docs/pdf.pdf
          git commit -m "Update generated PDF resume [$(date)]" || echo "No changes to commit"
          git push