name: Generate PDF Resume

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright
        run: |
          npm init -y
          npm install @playwright/test
          npx playwright install chromium
          npm install -D playwright

      - name: Generate PDF
        run: |
          mkdir -p docs
          cat > generate-pdf.js << 'EOL'
          const { chromium } = require('playwright');
          const path = require('path');

          (async () => {
            const browser = await chromium.launch();
            const context = await browser.newContext();
            const page = await context.newPage();
            
            const htmlPath = path.join(process.cwd(), 'index.html');
            await page.goto(`file://${htmlPath}`);
            
            // Ensure CSS is fully loaded
            await page.waitForLoadState('networkidle');
            
            await page.pdf({
              path: path.join(process.cwd(), 'docs/pdf.pdf'),
              format: 'A4',
              printBackground: true,
              margin: { top: 0, right: 0, bottom: 0, left: 0 }
            });
            
            await browser.close();
          })();
          EOL
          node generate-pdf.js

      - name: Commit and push PDF
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add -f docs/pdf.pdf
          git commit -m "Update generated PDF resume [$(date)]" || echo "No changes to commit"
          git push