name: Generate PDF Resume

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
          pip3 install weasyprint

      - name: Generate PDF
        run: |
          mkdir -p docs
          weasyprint index.html docs/pdf.pdf

      - name: Commit and push PDF
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add -f docs/pdf.pdf
          git commit -m "Update generated PDF resume [$(date)]" || echo "No changes to commit"
          git push